### PR TITLE
Delete files which conflict with versions moved to Boost.Graph

### PR DESCRIPTION
**Pull request by jzmaddock**

### CODE REVIEW

**Comment by jeking3** [comment]
Actually, this repository is now useless and needs to be removed from the submodules list.

**Comment by swatanabe** [comment]
AMDG

On 5/2/19 11:37 AM, James E. King III wrote:
> Actually, this repository is now useless and needs to be destroyed.
> 

No, that will break checkouts of old boost versions.
It will also lose history (unless you copied that as well?)

In Christ,
Steven Watanabe

**Comment by jzmaddock** [comment]
No I didn't copy history, I don't think there was much actually.

Plus the documentation files now point to the moved versions just in case anyone out there is linking to it.

**Comment by jeking3** [comment]
I did not preserve history, as that would have required a rebase and force push on boostorg/graph.  I amended my original comment indicating it should be removed from the list of submodules in the superproject.

**Pull request merged**
